name: speech_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  avatar_glow: ^2.0.2
  speech_to_text: ^6.3.0 #local package
  #google_sign_in: ^5.0.0
  flutter_text_box: ^0.0.1
  flutter_signin_button: ^2.0.0 #button style
  animated_text_kit: ^4.2.2 #animation
  #rounded_button: ^1.0.3 #buttonstyle
  firebase_core: ^2.13.0 #firebase authentication
  firebase_auth: ^4.6.1 #firebase authentication
  google_speech: ^2.2.0 #google cloud speech API (offloading)
  permission_handler: ^10.4.2 #permission to access audio from device storage
  #downloads_path_provider_28: ^0.1.2 #path to save file
  file_picker: ^5.3.2 #file upload
  googleapis: ^10.0.0
  googleapis_auth: ^1.4.1
  path_provider: ^2.0.15
  path: ^1.8.0
  http: ^0.13.3
  grpc: ^3.1.0
  protobuf: ^2.1.0
  fixnum: ^1.1.0
  meta: ^1.8.0
  sound_stream: ^0.3.0
  rxdart: ^0.27.3
  flutter_sound_lite: ^8.5.0
  raised_buttons: ^0.0.2
  #permission_handler: ^9.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/1.png
    - images/background.jpg
    - images/sound logo.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
